Add files via upload

diff --git a/bdl b/bdl
--- a/bdl
+++ b/bdl
@@ -1,4 +1,5 @@
 #!/bin/sh
+# Not POSIX. See shellcheck's output. Please make an ISSUE in xplshn/Handyscript if you know how to fix those issues in a sane way.
 
 # ANSI color codes
 GREEN='\033[0;32m'
@@ -10,18 +11,24 @@ INSTALL_DIR="$HOME/.local/share/bin"
 TEMP_DIR="/tmp"
 CACHE_FILE="/tmp/bdl_install-less_bins_cached"
 
-# Display a spinner loader with the colors declared(or not!) in the COOLSPINNERCOLOR variable
+# Display a spinner loader with default colors
 spinner() {
-    [ -z "$COOLSPINNER" ] && COOLSPINNER='|/~\\'
-    [ -z "$COOLSPINNER_COLOR" ] && COOLSPINNERCOLOR='\033[0m'
-    [ -z "$COOLSPINNER_DELAY"] && COOLSPINNER_DELAY=0.1
-    len=${#COOLSPINNER}
+    COOLSPINNER=${COOLSPINNER:-'|/~\\'}
+    COOLSPINNER_COLOR=${COOLSPINNER_COLOR:-'\033[0m'}
+    COOLSPINNER_DELAY=${COOLSPINNER_DELAY:-0.1}
+
+    len=$(printf "%s" "$COOLSPINNER" | wc -c | awk '{print $1}')
     trap 'printf "\033[?25h"; exit' INT
+
     while true; do
-        i=0
-        while [ "$i" -lt "$len" ]; do
-            char=$(printf "%s" "$COOLSPINNER" | cut -c "$((i + 1))")
-            [ -n "$COOLSPINNERCOLOR" ] && printf "%b%s%b" "$COOLSPINNERCOLOR" "$char" "\033[0m" || printf "%s" "$char"
+        i=1
+        while [ "$i" -le "$len" ]; do
+            char=$(printf "%s" "$COOLSPINNER" | cut -c "$i")
+            if [ -n "$COOLSPINNER_COLOR" ]; then
+                printf "%b%s%b" "$COOLSPINNER_COLOR" "$char" "\033[0m"
+            else
+                printf "%s" "$char"
+            fi
             sleep "$COOLSPINNER_DELAY"
             printf "\b"
             i=$((i + 1))
@@ -37,8 +44,7 @@ print_color() {
 fetch_binary() {
     package_name="$1"
     install_dir="$2"
-    custom_destination="$3"
-    destination="$install_dir/${3:-$package_name}" # Default destination
+    destination="${3:-$package_name}" # Default destination
 
     source_url=$(find_url "$package_name")
 
@@ -52,7 +58,7 @@ fetch_binary() {
     # Start spinner in the background
     spinner & spinner_pid=$!
 
-    if wget -O "$destination" "$source_url" && chmod +x "$destination"; then
+    if wget -O "$install_dir/$destination" "$source_url" && chmod +x "$install_dir/$destination"; then
         # Kill the spinner after download completes
         kill "$spinner_pid" >/dev/null 2>&1
         # Move the cursor to the beginning of the line and clear the line
@@ -174,7 +180,38 @@ list_packages() {
     printf "\033[2K\r%s\n" "$packages"
 }
 
+bootstrap() {
+    # Function to fetch binaries using wget
+    fetch_wget_binary() {
+        package_name="$1"
+        destination="$TEMP_DIR/bdl_bootstrap/$package_name"
+        source_url="https://raw.githubusercontent.com/Azathothas/Toolpacks/main/$(uname -m)/$package_name"
+        mkdir -p $TEMP_DIR/bdl_bootstrap
+
+        wget -O "$destination" "$source_url" &&
+        chmod +x "$destination" &&
+        export PATH="/tmp/bdl_bootstrap:$PATH" ||
+        printf "Failed to fetch %s.\n" "$package_name"
+    }
+
+    if ! command -v curl >/dev/null 2>&1; then
+        printf "curl is not installed. Bootstrapping...\n"
+        fetch_wget_binary "curl"
+    fi
+
+    if ! command -v jq >/dev/null 2>&1; then
+        printf "jq is not installed. Bootstrapping...\n"
+        fetch_wget_binary "jq"
+    fi
+
+    if ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
+        printf "Please install curl & jq manually to avoid bootstrapping in the future.\n"
+    fi
+}
+
 # Main script
+bootstrap
+
 case $1 in
     run)
         fetch_and_run "$2" "${@:3}"
